{% set version = "0.1.1.0" %}

package:
  name: evalhyd-cli
  version: {{ version }}

source:
  url: https://gitlab.irstea.fr/HYCAR-Hydro/evalhyd/evalhyd-cli/-/archive/v{{ version }}/evalhyd-cli-v{{ version }}.tar.gz
  sha256: 553eda042d5474fda262abff879cce6f06743e71a1738cdfb8fad699a5f86304

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.15
    - ninja
  host:
    - xtl >=0.7.5
    - xtensor >=0.24.6
    - cli11 >=2.3.1
    - libevalhyd ==0.1.1

test:
  commands:
    - evalhyd -h
    - evalhyd evald -h
    - evalhyd evalp -h

about:
  home: https://hydrogr.github.io/evalhyd
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENCE.rst
  summary: A command line interface for evalhyd, a C++ library to evaluate streamflow predictions
  description: |
    An command line executable to evaluate deterministic and 
    probabilistic streamflow predictions
  doc_url: https://hydrogr.github.io/evalhyd/cli
  dev_url: https://gitlab.irstea.fr/HYCAR-Hydro/evalhyd/evalhyd-cli

extra:
  recipe-maintainers:
    - fbourgin
    - ThibHlln
